Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace TelegramSupportSendMsg.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.Net;
using System.Web;
using Microsoft.AspNetCore.Identity;

namespace TelegramSupportSendMsg.Pages
{
    public class IndexModel : PageModel
    {

        [BindProperty]
        public InputModel Input { get; set; }
        public class InputModel
        {

            [Required]
            [DataType(DataType.Text)]
            [Display(Name = "Name")]
            public string Name { get; set; }

            [Required]
            [DataType(DataType.Text)]
            [Display(Name = "Branch")]
            public string Branch { get; set; }

            [Required]
            [DataType(DataType.PhoneNumber, ErrorMessage = "Not a number")]
            [Display(Name = "Phone Number")]
            public string PhoneNum { get; set; }

            [Required]
            [DataType(DataType.Text)]
            [Display(Name = "Department")]
            public string Department { get; set; }

            [Required]
            [DataType(DataType.Text)]
            [Display(Name = "Machine Type")]
            public string MacType { get; set; }

            [Required]
            [DataType(DataType.Text)]
            [Display(Name = "Machine ID")]
            public string MacId { get; set; }

            [Required]
            [DataType(DataType.Text)]
            [Display(Name = "Issue")]
            public string Issue { get; set; }

            [Required]
            [DataType(DataType.Text)]
            [Display(Name = "Telegram Bot ID")]
            public string BotId { get; set; }

            [Required]
            [DataType(DataType.Text)]
            [Display(Name = "Telegram Chat ID")]
            public string ChatId { get; set; }

        }

        public string Message
        {
            get;
            set;
        }

        public IActionResult OnPostSubmit(InputModel Input)

        {
            if (ModelState.IsValid)
            {
                var user = User.Identity.Name;
                string strUser = user.Substring(0, 3);
                var Customer = "";

                if (strUser == "Sys")
                {
                    Customer = "SYSADMIN";
                }
                

                Message = "-------// New Issue //------- \n"
                          + "Customer : " + Customer + " \n"
                          + "User ID : " + user + " \n"
                          + "Name : " + Input.Name + " \n"
                          + "Branch : " + Input.Branch + " \n"
                          + "Phone Number : " + Input.PhoneNum + " \n"
                          + "Department : " + Input.Department + " \n"
                          + "Machine Type : " + Input.MacType + " \n"
                          + "Machine ID : " + Input.MacId + " \n"
                          + "Issue : " + Input.Issue + " \n"
                          + "-------//    End    //-------";

                //
                WebRequest req = WebRequest.Create("https://api.telegram.org/bot" + Input.BotId + "/sendMessage?chat_id=@" + Input.ChatId + "&text=" + HttpUtility.UrlEncode(Message));
                req.UseDefaultCredentials = true;
                var result = req.GetResponse();
                req.Abort();

                return RedirectToPage("/Success");
            }

            return Page();
        }

    }

}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TelegramSupportSendMsg.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Success.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TelegramSupportSendMsg.Pages
{
    public class SuccessModel : PageModel
    {
        public void OnGet()
        {
        }

        public RedirectToPageResult OnPost()
        {
            return RedirectToPage("/Index");
        }
    }
}

Pages/Index.cshtml
@page
@model IndexModel
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@{
    ViewData["Title"] = "Home page";
}

@if (SignInManager.IsSignedIn(User))
{
    <div class="text-center">
        <h1 class="display-4">Service Request Portal</h1>
        <p class="m-3 font-weight-bold">Please fill in all details and press submit</p>
        @*<p>Support Portal</p>*@
        @*<div class="row">
            <div class="col-md-5 mx-auto">*@
    <section>
        <form id="request" method="post">
            @*<div asp-validation-summary="All" class="text-danger"></div>*@
            <div class="form-inline m-1">
                <label asp-for="Input.Name" class="col-4 justify-content-end"></label>
                <input asp-for="Input.Name" class="form-control col-4" />
                &nbsp; <span asp-validation-for="Input.Name" class="text-danger"></span>
            </div>
            <br />
            <div class="form-inline m-1">
                <label asp-for="Input.Branch" class="col-4 justify-content-end"></label>
                <input asp-for="Input.Branch" class="form-control col-4" />
                &nbsp; <span asp-validation-for="Input.Branch" class="text-danger"></span>
            </div>
            <br />
            <div class="form-inline m-1">
                <label asp-for="Input.PhoneNum" class="col-4 justify-content-end"></label>
                <input asp-for="Input.PhoneNum" max="10" class="form-control col-4" />
                &nbsp; <span asp-validation-for="Input.PhoneNum" class="text-danger"></span>
            </div>
            <br />
            <div class="form-inline m-1">
                <label asp-for="Input.Department" class="col-4 justify-content-end"></label>
                <input asp-for="Input.Department" class="form-control col-4" />
                &nbsp; <span asp-validation-for="Input.Department" class="text-danger"></span>
            </div>
            <br />
            <div class="form-inline m-1">
                <label asp-for="Input.MacType" class="col-4 justify-content-end"></label>
                <input asp-for="Input.MacType" class="form-control col-4" />
                &nbsp; <span asp-validation-for="Input.MacType" class="text-danger"></span>
            </div>
            <br />
            <div class="form-inline m-1">
                <label asp-for="Input.MacId" class="col-4 justify-content-end"></label>
                <input asp-for="Input.MacId" class="form-control col-4" />
                &nbsp; <span asp-validation-for="Input.MacId" class="text-danger"></span>
            </div>
            <br />
            <div class="form-inline m-1">
                <label asp-for="Input.Issue" class="col-4 justify-content-end"></label>
                <textarea asp-for="Input.Issue" class="form-control col-4" rows="4"></textarea>
                &nbsp; <span asp-validation-for="Input.Issue" class="text-danger"></span>
            </div>
            <br />
            <label class="col-4 justify-content-end">*Enter Telegram Bot ID and Chat ID</label>
            <br />
            <div class="form-inline m-1">
                <label asp-for="Input.BotId" class="col-4 justify-content-end"></label>
                <input asp-for="Input.BotId" class="form-control col-4" rows="4" />
                &nbsp; <span asp-validation-for="Input.BotId" class="text-danger"></span>
            </div>
            <br />
            <div class="form-inline m-1">
                <label asp-for="Input.ChatId" class="col-4 justify-content-end"></label>
                <input asp-for="Input.ChatId" class="form-control col-4" rows="4" />
                &nbsp; <span asp-validation-for="Input.ChatId" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                @*<button type="submit" class="btn btn-primary col-4">Submit</button>*@
                <input type="submit" class="btn btn-primary col-4" value="Submit" asp-page-handler="Submit" />
            </div>
        </form>
        @*<form method="post">
            <input asp-for="Message" />
            <br />
            <input type="submit" />
        </form>*@
    </section>
        @*</div>
            </div>*@
    </div>
}
else
{
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <div class="text-center">
        <h1 class="display-4">Welcome</h1>
        <h2>Service Request Portal</h2>
    </div>
    <div class="text-center">
        @*<a href="#" style="background-image: @Url.Content("~/Images/logo.png")"></a>*@
        @*<a href="#" style="background-image: url('~/Images/logo.png')"></a>*@
        @*<img src="~/Images/logo.png" />*@
    </div>
}

Pages/Success.cshtml
@page
@model SuccessModel
@{
    ViewData["Title"] = "Success";
}

<h1 class="text-success">The service request has been submitted successfully.</h1>
<h2 class="text-success">Thank you.</h2>
<br />
<form id="success" method="post">
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Submit Another Request</button>
    </div>
</form>